let productTempData = [
  {
    page: 1,
    seq: 0,
    fileName: "shoes1.jpg",
    title: "[Nike] Green and Blue",
    info: "새로운 에어의 시대에 오신 것을 환영합니다.",
    dtlInfo: `차세대 에어 기술을 만나보세요. 에어맥스 Dn은 이중 압력 튜브의 다이내믹 에어 유닛 시스템을 갖추고 있어 걸음마다 반환력이 뛰어난 착화감을 선사합니다. 덕분에 아침부터 밤까지 착용해도 될 만큼 편안한 퓨처리스틱 디자인이 탄생했죠. 믿기 힘든 착화감을 직접 느껴보세요.`,
    review: [
      { title: "GOOD!", content: "GOOD2222" },
      { title: "이뻐요", content: "좋습니다." },
    ],
    price: 189000,
  },
  {
    page: 1,
    seq: 1,
    fileName: "shoes2.jpg",
    title: "[Nike] Red and White",
    info: "글로벌 신발인을 꿈꾼다.",
    dtlInfo: `끈을 조이고 나이키만의 유산을 느껴보세요. 예술, 음악, 문화의 교차점에서 생산된 이 챔피언 러닝화는 90년대를 정의하는 제품입니다. 여러 대통령이 착용하고, 컬래버레이션을 통해 혁신을 이루었으며, 독특한 컬러웨이로 찬사를 받은 이 신발은 충격적인 비주얼, 와플 밑창과 노출형 나이키 에어 쿠셔닝을 그대로 재현합니다.`,
    review: [{ title: "이뻐요", content: "근데 중국산이네" }],
    price: 85000,
  },
  {
    page: 1,
    seq: 2,
    fileName: "shoes3.jpg",
    title: "[Nike] Pink bell",
    info: "에어를 신고 걸어본 적이 있나요? ",
    dtlInfo: `에어 베이퍼맥스 2023을 신고 직접 느껴보세요. 천공 처리된 깔창을 통해 혁신적인 기술력을 엿볼 수 있습니다. 밖으로 꺼내어 더 자세히 살펴보세요. 신축성이 뛰어난 플라이니트 갑피는 무게 기준 20% 이상 재생 소재로 제작되었습니다.`,
    review: [{ title: "GOOD!", content: "GOOD2222" }],
    price: 189000,
  },
  {
    page: 2,
    seq: 3,
    fileName: "shoes4.jpg",
    title: "[Convers] Green and AllStar",
    info: "Made in Korea",
    dtlInfo: "",
    review: [{ title: "GOOD!", content: "GOOD2222" }],
    price: 99000,
  },
  {
    page: 2,
    seq: 4,
    fileName: "shoes5.jpg",
    title: "[Nike] Basic v01",
    info: "Made in China",
    dtlInfo: "",
    review: [{ title: "GOOD!", content: "GOOD2222" }],
    price: 70000,
  },
  {
    page: 2,
    seq: 5,
    fileName: "shoes6.jpg",
    title: "[LOWA] GORE-TEX",
    info: "Made in Korea",
    dtlInfo: "",
    review: [{ title: "GOOD!", content: "GOOD2222" }],
    price: 350000,
  },
  {
    page: 3,
    seq: 6,
    fileName: "shoes7.jpg",
    title: "[Convers] Red and AllStar",
    info: "Made in Korea",
    dtlInfo: "",
    review: [{ title: "GOOD!", content: "GOOD2222" }],
    price: 99000,
  },
  {
    page: 3,
    seq: 7,
    fileName: "shoes8.jpg",
    title: "[Convers] Green and AllStar_Imitation",
    info: "Made in China",
    dtlInfo: "",
    review: [{ title: "GOOD!", content: "GOOD2222" }],
    price: 20000,
  },
  {
    page: 3,
    seq: 8,
    fileName: "shoes9.jpg",
    title: "[ASICS] Red Fit",
    info: "Made in Japan",
    dtlInfo: "",
    review: [{ title: "GOOD!", content: "GOOD2222" }],
    price: 165000,
  },
];

export default productTempData;
